name: Build GPTK
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 19 * * *"
jobs:
  build_gptk:
    name: Build GPTK
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tap homebrew-apple
        run: brew tap apple/apple http://github.com/Whisky-App/homebrew-apple
      - name: Install taps
        run: brew install apple/apple/game-porting-toolkit winetricks
      - name: Trim Files
        run: |
          rm -rf $(brew --prefix game-porting-toolkit)/.brew
          rm -rf $(brew --prefix game-porting-toolkit)/include
          rm -rf $(brew --prefix game-porting-toolkit)/INSTALL_RECEIPT.json
          rm -rf $(brew --prefix game-porting-toolkit)/share/man
          find $(brew --prefix game-porting-toolkit)/bin -type f -not -name "wine64" -not -name "wine64-preloader" -not -name "wineserver" -delete
          find $(brew --prefix game-porting-toolkit)/bin -type l -delete
      - name: Make Libraries folder
        run: |
          mkdir -p Libraries/Wine
      - name: Copy taps
        run: |
          cp -a $(brew --prefix game-porting-toolkit)/. Libraries/Wine/
          cp -a $(brew --prefix winetricks)/bin/winetricks Libraries/
      - name: Copy external deps
        run: |
          cp -a libs/. Libraries/Wine/lib/
      - name: Copy DXVK
        run: |
          cp -a DXVK Libraries/
      - name: Copy Version .plist
        run: |
          cp -a GPTKVersion.plist Libraries/
      - name: Install GPTK
        run: |
          ditto GPTK/redist/lib/ Libraries/Wine/lib/
          ln -s ./external/libd3dshared.dylib Libraries/Wine/lib/libd3dshared.dylib
          ln -s ./external/D3DMetal.framework Libraries/Wine/lib/D3DMetal.framework
      - name: Tar Libraries
        run: |
          tar -zcf Libraries.tar.gz Libraries
      - name: Upload Libraries
        uses: actions/upload-artifact@v3
        with:
          name: Libraries
          path: Libraries.tar.gz
